### ISSUE TITLE
No rule to make target 'scanf-examples.c'

### ISSUE THREAD

**Issue by gooofy** [aros-development-team/AROS#110]
**Describe the bug**
Compilation from source fails on CentOS 8 x86_64

**To Reproduce**
1. git clone AROS
2. ./configure --prefix=/home/guenter/projects/amiga/aros
3. make
[...]

[MMAKE] Making test-crt-posixc-posix1-scanf in developer/debug/test/crt/posixc
make[1]: *** No rule to make target 'scanf-examples.c', needed by '/home/guenter/projects/amiga/aros/src/AROS/bin/linux-x86_64/gen/developer/debug/test/crt/posixc/scanf-examples.o'.  Stop.
[MMAKE] make --no-print-directory TOP=/home/guenter/projects/amiga/aros/src/AROS SRCDIR=/home/guenter/projects/amiga/aros/src/AROS CURDIR=developer/debug/test/crt/posixc TARGET=test-crt-posixc-posix1-scanf --file=mmakefile test-crt-posixc-posix1-scanf failed: 512
[MMAKE] Error: Error while running make in developer/debug/test/crt/posixc: No such file or directory

**Architecture**
 - linux (hosted)
 
**CPU**
 - x86_64

**Comment by stanman29** [comment]
I had the same problem for two weeks until I saw that this c source file is part of a git submodule. Please update all submodules by running this command at the prompt. 
git submodule update --init --recursive

**Comment by gooofy** [comment]
Hey, that was it, it works! Thanks so much :)
