### ISSUE TITLE
Misc fixes

### ISSUE THREAD

**Issue by deadw00d** [aros-development-team/AROS#116]
Hello,

Attached please find a patch set with fixes to:
AHI (64bit)
alsa.audio (better functionality)
hosted kernel cleanup
MUI (compatibility fix)

I'd appreciate if these fixes would be applied to master

[fixes.zip](https://github.com/aros-development-team/AROS/files/4605667/fixes.zip)

**Comment by Kalamatee** [comment]
It would be better if you can apply the changes in branches on a fork, and issue pull requests so the work is correctly attributed to yourself.

**Comment by deadw00d** [comment]
I believe if git am is used to apply the patchset, I will be preserved as an author with some other person as committer.

Is using fork/pull requests considered a strict requirement or will patches in this form be also accepted?

**Comment by Kalamatee** [comment]
Its not a strict requirement, but is easier for others to review/merge the changes (some people are not too familiar with git or its workflow)

**Comment by Kalamatee** [comment]
I have applied the patches. Thanks.

**Comment by deadw00d** [comment]
Thank you as well.
