### ISSUE TITLE
mkamikeymap tool trashes memory

### ISSUE THREAD

**Issue by michalsc** [aros-development-team/AROS#118]
**Describe the bug**
When processing deadkey combinations the mkamikeymap tool uses a fixed length buffer with size of 32 bytes:

```
BOOL processSectDeadkey(struct config *cfg, FILE *descf)
{
    UBYTE dkbuffer[32], *buffptr;
```

When the deadkey combinations exceed this length the tool happily continues to fill the memory behind the buffer thus trashing ram and eventually causing segmentation fault. As a temporary solution I will increase the buffer to 512 bytes, but in future we should maybe use dynamic solution (malloc + realloc)

**Comment by Kalamatee** [comment]
resolved in trunk
