### ISSUE TITLE
Copymem 68080 is buggy

### ISSUE THREAD

**Issue by Lynxxde** [aros-development-team/AROS#128]
Hi,

while working on http://aminet.net/package/util/boot/CopyMemAIO i wanted to add support for 68080 and found the copymem here:
https://github.com/aros-development-team/AROS/blob/master/arch/m68k-all/exec/copymem_ac080.S
 
And from what i read about vampire this "simple" copymem should be an optimal solution (two move.l (an)+,(am)+ will be joined to a single command on 68080), so i based my code on this but i noticed it does "dbf %d0,blit_up_fast_xloop" in Row 93, this means it can only copy 512Kb of ram. Either change it to "subq.l #1,%d0" & "bne.b blit_up_xloop" or convert my code from the aminet-archive, because i did some other optizations to the startingcode aswell ..

with kind regards, Holger Hippenstiel

**Comment by Kalamatee** [comment]
should be fixed in commit 0e70ee5

**Comment by Lynxxde** [comment]
Oops, nearly forgot about this .. Sorry, but my quickly suggested fix is wrong, dbf %d0, counts to till d0 is -1, my "fix" counts only to zero, so to really fix it please change the "bne.b blit_up_fast_xloop" to "bpl.b blit_up_fast_xloop". Sorry for the inconvience.
