### ISSUE TITLE
Screen title not aligned as menu (68k native video)

### ISSUE THREAD

**Issue by hth313** [aros-development-team/AROS#15]
The text inside a screen title bar is placed slightly high. When the menu is opened, the menu title texts are better centered. If one has the same initial text in both, the effect is not so nice as the text moves down and up, it should probably look better if it stayed in the same position.

This happens on a standard Amiga running native video at least, I have not examined other variants.

**Comment by Kalamatee** [comment]
this has been adjusted in master.
