### ISSUE TITLE
locale.prefs and icontrol.prefs incompatible with the genuine amiga counterparts.

### ISSUE THREAD

**Issue by wawatok** [aros-development-team/AROS#38]
running the genuine amiga installation (wb3.9) from aros kickstart these both files seem not to be correctly interpreted. system hangs.

**Comment by Kalamatee** [comment]
wont be fixed:

AROS uses different naming convention for locale prefs (plain english file names) to prevent issues with different filesystems. Icontrol exposes different options to the default AmigaOS flavour.
