### ISSUE TITLE
elf2hunk generates wrong relocation info

### ISSUE THREAD

**Issue by michalsc** [aros-development-team/AROS#44]
AROS tool, elf2hunk, generates wrong relocation in case of R_68_PC32. The partial relocation done in this tool seems to be correct, but the relocation is copied into RELOC32 which is absolutely wrong.

Correct behaviour is to copy the R_68_PC32 into RELRELOC32, or to eliminate R_68_PC32 completely if both relocation and symbol are in the very same hunk.

**Comment by MBeijer** [comment]
@michalsc mark this as done?

**Comment by michalsc** [comment]
@MBeijer not yet, there are two fixes pending. The relocation info is fixed now, but:
a) the PC-relative relocation data can be skipped entirely if performed within the same hunk
b) Currently the RELREL hunk is generated always, even if it's going to be empty.

**Comment by MBeijer** [comment]
Ah :)
Btw, I think if you include  #44 in your commits related to this issue, it will show up here.

**Comment by Kalamatee** [comment]
Most AmigaOS programs have no idea about RELRELOC32, and likely AmigaOS's own hunk loader also doesn't handle it (untested).

**Comment by michalsc** [comment]
Elf2Hunk does not support R_68K_PC16 within the *same* section. It throws an error instead of silently skipping this reloc. It should error only if the relocation crosses hunk boundary

**Comment by Kalamatee** [comment]
closing: Michal has fixed elf2hunk in commit 204dd06,  and commit c7a92db fixes incorrect handling of rereloc32 in loadseg.
