### ISSUE TITLE
Non-US keyboards don't work on X86_64 hosted

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#53]
Something is wrong with X11 keyboard handling.

For French and German (and likely other) keyboards some keys aren't working (e.g. German umlauts äüö).

See
https://ae.amigalife.org/index.php?PHPSESSID=f4rb7d5i2loevlim905gh7o2g3&topic=430.msg3869#new

**Comment by Kalamatee** [comment]
there seems to be a more general issue with the input settings. Changing to e.g. German here results in hosted crashing when you go to save.

**Comment by mattrust** [comment]
Fixed by Kalamatee with:
https://github.com/aros-development-team/AROS/commit/37ef1658402e85ebaffd9a01f05d4d072b89e521
