### ISSUE TITLE
MoveScreen() crashes with a Screen which was created with SA_Behind, TRUE

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#553]
- [ ] **Describe the bug**<br/>
Calling MoveScreen() on a screen which was opened with SA_Behind, TRUE crashes in Compositor HIDD.

- [ ] **To Reproduce**<br/>
1.open a Shell and run SYS:Developer/Debug/Test/Intuition/MoveScreen

- [ ] **Expected behaviour**<br/>
Just no crash.

- [ ] **Screenshots**<br/>

- [ ] **Architecture**<br/>
 - linux (hosted)
 
Not yet tested:
 - Amiga (including UAE, Vampire cards)
 - pc (native)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
- [ ] **CPU**<br/>
 - x86_64

Not yet tested: 
 -  i386
 - m68k
 - arm
 - ppc
 - other:

- [ ] **Version**<br/>
Provide the Git ID from AboutAROS (call menu Wanderer>AROS>About)

- [ ] **Additional context**<br/>

#0  0x000000005f61ee60 in OOP_16_OOP_GetAttr (object=0x0, attrID=20480, storage=0x41a7be00, OOPBase=0x410599d0) at /home/mazze/projects/aros-src/rom/oop/./getattr.c:74
#1  0x00000000412290fa in __inline_OOP_OOP_GetAttr (__arg1=0x0, __arg2=20480, __arg3=0x41a7be00, __OOPBase=0x410599d0) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/include/inline/oop.h:163
#2  0x000000004122bb5d in X11Cl__Hidd_Gfx__CopyBox (cl=0x41178908, o=0x41223f38, msg=0x41a7beb0) at /home/mazze/projects/aros-src/arch/all-hosted/hidd/x11/./x11gfx_hiddclass.c:712
#3  0x000000005f6213f8 in HIDD_DoMethod (o=0x41223f38, msg=0x41a7beb0) at /home/mazze/projects/aros-src/rom/oop/./hiddmetaclass.c:575
#4  0x00000000411fa584 in HIDD_Gfx_CopyBox_ (__HiddGfxBase=4, __obj=0x41223f38, src=0x418839f8, srcX=0, srcY=0, dest=0x0, destX=0, destY=0, width=800, height=600, gc=0x41111038) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/interface/Hidd_Gfx.h:420
#5  0x00000000411fb0cd in HIDDCompositorRedrawBitmap (compdata=0x41110c98, renderTarget=0x0, n=0x410e9e10, rect=0x41a7c038) at /home/mazze/projects/aros-src/workbench/devs/monitors/Compositor/./compositor_class.c:298
#6  0x00000000411fb88c in HIDDCompositorRedrawVisibleRegions (compdata=0x41110c98, drawrect=0x0) at /home/mazze/projects/aros-src/workbench/devs/monitors/Compositor/./compositor_class.c:453
#7  0x00000000411fe073 in Compositor__Hidd_Compositor__BitMapPositionChange (cl=0x41110998, o=0x41110c98, msg=0x41a7c1c0) at /home/mazze/projects/aros-src/workbench/devs/monitors/Compositor/./compositor_class.c:1414
#8  0x000000005f6213f8 in HIDD_DoMethod (o=0x41110c98, msg=0x41a7c1c0) at /home/mazze/projects/aros-src/rom/oop/./hiddmetaclass.c:575
#9  0x000000005f55c9b6 in compositor_ScrollBitMap (o=0x41110c98, bitmap=0x410eb848, x=0x41a7c238, y=0x41a7c230, GfxBase=0x41067200) at /home/mazze/projects/aros-src/rom/graphics/./compositor_driver.h:29
#10 0x000000005f55cb25 in Graphics_98_ScrollVPort (vp=0x4108f228, GfxBase=0x41067200) at /home/mazze/projects/aros-src/rom/graphics/./scrollvport.c:92
#11 0x000000005f5a5201 in __inline_Graphics_ScrollVPort (__arg1=0x4108f228, __GfxBase=0x41067200) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/graphics.h:1543
#12 0x000000005f5a52c9 in Intuition_132_ScreenPosition (screen=0x4108f1e0, flags=0, x1=0, y1=1, x2=0, y2=0, IntuitionBase=0x4107e0d0) at /home/mazze/projects/aros-src/rom/intuition/./screenposition.c:91
#13 0x000000005f598726 in __inline_Intuition_ScreenPosition (__arg1=0x4108f1e0, __arg2=0, __arg3=0, __arg4=1, __arg5=0, __arg6=0, __IntuitionBase=0x4107e0d0) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/intuition/intuition/include/inline/intuition.h:1969
#14 0x000000005f598774 in Intuition_27_MoveScreen (screen=0x4108f1e0, dx=0, dy=1, IntuitionBase=0x4107e0d0) at /home/mazze/projects/aros-src/rom/intuition/./movescreen.c:55
#15 0x0000000041170b63 in __inline_Intuition_MoveScreen (__arg1=0x4108f1e0, __arg2=0, __arg3=1, __IntuitionBase=0x4107e0d0) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/intuition.h:353
#16 0x0000000041170dac in main () at /home/mazze/projects/aros-src/developer/debug/test/intuition/./movescreen.c:41

In frame 2:
OOP_GetAttr(msg->dest, aHidd_BitMap_X11_Drawable, (IPTR *) &dest);

msg->dest is NULL

**Comment by DerThore** [comment]
Moving screens on the vampire will also show no good result, when having more than one screen. The screen turns blank, and you cannot see the screen contents

**Comment by Kalamatee** [comment]
Still crashing on pc-x86_64 - need to investigate.

**Comment by Kalamatee** [comment]
Fix applied. Tested under linux-x86_64, mingw32-i386 and pc-x86_64
