### ISSUE TITLE
broken binaries with uninitialized global variables

### ISSUE THREAD

**Issue by sezero** [aros-development-team/AROS#577]
```c
#include <proto/exec.h>
struct Library *SocketBase;
int main (void) {
  SocketBase = OpenLibrary((CONST_STRPTR)"bsdsocket.library", 0);
  return !!SocketBase;
}
```

Building the minimal reproducer above like the following,
```
$ x86_64-aros-gcc -O2 -Wall -c 1.c
$ x86_64-aros-gcc -o test 1.o -Wl,-Map,map.txt
```

... results in a broken binary: Attempting to run the result in
workbench shell outputs `file not executable`.  Attached the map
file output by ld: [map.txt](https://github.com/aros-development-team/AROS/files/8354570/map.txt) - There is no reference to `SocketBase`,
but you can see the COMMON section discarded.
```
Discarded input sections

 COMMON         0x0000000000000000        0x0 1.o
```

Only if I build with `-fno-common`, then the resulting binary is
usable.

This is with the default gcc-6.5.0/binutils-2.32 x86_64-aros 
toolchain available from the aros download site (2022-03-25.)

**Comment by Kalamatee** [comment]
The toolchains on the download page are not really ready for normal usage, and as you have noticed do not use flags that are required to produce working binaries (which are normally provided by the AROS build system). There is also no SDK to use with the toolchains just yet.

They "can" be used - but you will need to check the correct CFLAGS, etc, to use with them.
