### ISSUE TITLE
SysInfo gives a wrong 'Horiz KHz' and 'Vert Hz' values with AROS ROM

### ISSUE THREAD

**Issue by wawatok** [aros-development-team/AROS#58]
submitted by ShK

tested on WinUAE with stock A1200+4MB settings
and nightly AROS floppy http://www.aros.org/nightly1.php
with SysInfo floppy https://sysinfo.d0.se/

![](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fusercontent.irccloud-cdn.com%2Ffile%2FgYR49S3s%2Faros.png)

**Comment by Kalamatee** [comment]
Without details about where/how it gets this information, there is no way for us to know if it is a problem in AROS or just a bug in how it calculates those. It is unlikely to get any attention because of this.

**Comment by Kalamatee** [comment]
Further details indicated this was due mainly to the AmigaVideo driver providing incomplete sync information for the display modes. I've added the necessary data now in commit 4c5584478475724e390388ec32bd570a507e9bae and testing shows the correct values in apps.
