### ISSUE TITLE
Hosted mingw environment x86_64 crashes when bootstrapping

### ISSUE THREAD

**Issue by gbraad** [aros-development-team/AROS#586]
**Describe the bug**
Bootstrapping fails

**To Reproduce**
1. Go to `C:\...\AROS-20220627-mingw32-x86_64-system\boot\mingw32`
2. Click on `AROSBootstrap.exe`

**Expected behaviour**
Startup happens

**Screenshots**
```
C:\Users\gbraad\Downloads\AROS-20220627-mingw32-x86_64-system\AROS-20220627-mingw32-x86_64-system\boot\mingw32>AROSBootstrap.exe
[Bootstrap] RAM memory block allocated: 000000000A250000 - 000000001A250000 (268435456 bytes)
[KRN] Exception 0x00000000, SysBase 0x000000000a250740, KernelBase 0x000000000a251b90
[KRN] Task 0x000000000a281270 (Exec Bootstrap Task)
    ContextFlags: 0x00000000
    RSP=000000006b641956  RBP=000000000245f580  RIP=000000000a250740
    RAX=000000001a25b6a1  RBX=000000001a250000  RCX=00001fb2417dbc05  RDX=000000001a261115
    R08=000000001a25fb27  R09=0000000000000003  R10=000800011a268e40  R11=000000000245f860
    R12=000000001a25b6a1  R13=000000000a282210  R14=000000000ffc33b0  R15=000000001a250000
    RDI=000000000a28c3e0  RSI=000000000a250740  EFLAGS=00000000
[KRN] **UNHANDLED EXCEPTION 0x00080001** stopping here...
```

**Architecture**
 - windows(hosted)
 - mingw
 
**CPU**
 - i386
 - x86_64

**Version**
Unable to open.
https://aros.sourceforge.io/nightly1.php ->
https://sourceforge.net/projects/aros/files/nightly2/20220627/Binaries/AROS-20220627-mingw32-x86_64-system.tar.bz2/download

**Additional context**
the i386 version works
https://sourceforge.net/projects/aros/files/nightly2/20220629/Binaries/AROS-20220629-mingw32-i386-system.tar.bz2/download

**Comment by magorium** [comment]
@gbraad:
1. why the double AROS-20220627-mingw32-x86_64-system ?
2. AROS needs to be started from the sys directory, then invoked with boot\mingw32\AROSBootstrap.exe

With regards to 2: I don't know Windows nor do I know how you have setup your directories because of 1. The thing I do know is that you can make a (desktop) link for it as well, invoking the bootstrap executable from within the correct directory (in case if that makes life easier for you).

If you start the bootstrap from the incorrect location when using the i386 hosted version it will "crash" the same way.

**Comment by gbraad** [comment]
They are not the same. One is the 32bit and the other is the 64bits version.

**Comment by gbraad** [comment]
> If you start the bootstrap from the incorrect location ... it will "crash" the same way.

Is this documented? Can't recall seeing this

**Comment by magorium** [comment]
The crash itself is not documented. But how you start AROS is, see http://www.aros.org/documentation/users/installation.php#running

And wrt to the directory, you seem to have embedded the aros directory from the archive into the same directory again. Therefor it is undetermined where actually your SYS; directory exists on your disk and thus not able to determine where your sys: directory is actually located.

**Comment by Kalamatee** [comment]
> > If you start the bootstrap from the incorrect location ... it will "crash" the same way.
> 
> Is this documented? Can't recall seeing this

It is neither documented, nor true. You can directly launch the windows hosted version by double clicking on the exe.

The issue you have opened the ticket for is known and expected currently. The build has been enabled to get it working, which has never been the case. If you would like to use the windows hosted version it is advised, for the time being at least, to use the 32bit version - however please note the windows hosted version is considerably more unstable than e.g linux hosted.
