### ISSUE TITLE
SysMon gurus on Processor tab

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#588]
**Describe the bug**
SysMon shows alert when clicking on Processors tab.

**To Reproduce**
1. Start AROS (a debug build with mungwall) 
2. Start SYS:System/SysMon
3. Click on the "Processors" tab

**Expected behaviour**
Don't show alert.

**Screenshots**
![sysmon_guru](https://user-images.githubusercontent.com/18250926/184113307-48558820-2104-46ed-b80c-3f1397c29bd0.png)

**Architecture**
 - linux (hosted)
 
Not yet tested:
 - Amiga (including UAE, Vampire cards)
 - pc (native)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
**CPU**
 - x86_64
 
Not yet tested:
 - i386
 - m68k
 - arm
 - ppc
 - other:

**Version**
Provide the Git ID from AboutAROS (call menu Wanderer>AROS>About)

**Additional context**
*** Logged alert:
Program failed
Task : 0x0000000041CBC9B0 - SysMon
Error: 0x0100000C - Sanity check on memory list failed
PC   : 0x0000000041D45192
Module System:Classes/Zune/Graph.mcc Segment 1 .text (0x0000000041D44680) Offset 0x0000000000000B12
Mungwall data:
In FreeMem, block at 0x0000000040007fd0, size 1225440
Allocated using AllocMem by task 0x0000000041cbc9b0 (SysMon) at 0x0000000041d45157
Module System:Classes/Zune/Graph.mcc Segment 1 .text (0x0000000041D44680) Offset 0x0000000000000AD7
FreeMem size 408480 mismatch

Disassembly:

0x0000000000000000 ******************************** <illegal address>

**Comment by Kalamatee** [comment]
should be fixed by 7566c4a5666a470417d754fd9c2c0a81a921966e

**Comment by mattrust** [comment]
It works.
