### ISSUE TITLE
mingw32-i386-system nightly builds fail to launch

### ISSUE THREAD

**Issue by ccawley2011** [aros-development-team/AROS#599]
**Describe the bug**
Attempting to launch the mingw32-i386-system nightly build fails, and reports the following message in the command line:
```
[Kernel] Failed to load host-side module: The specified module could not be found.
```

**To Reproduce**
1. Launch AROS using `./boot/mingw32/AROSBootstrap.exe`

**Architecture**
 - mingw
 
**CPU**
 - i386

**Version**
Nightly build from 2023/01/09

**Additional context**
The problem seems to be caused by some of the host libraries linking with `LIBGCC_S_DW2-1.DLL` to provide `__udivdi3` and `__umoddi3`, which isn't included in the archive.

**Comment by Kalamatee** [comment]
It looks like something has changed with regards to mingw32 - we may need to use -static-libgcc and -static-libstdc++ when building the host side dll's.

**Comment by Kalamatee** [comment]
There also appears to be a typo in the mmakefile.src for the kernel.dll, which appears to cause "-Winline" to be unused.

**Comment by Kalamatee** [comment]
Tested and working
