### ISSUE TITLE
RENAME bla bla/ corrupts RAM:

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#612]
**Describe the bug**
An attempt to rename a directory on RAM: to its parent directory (e.g. RENAME bla bla/) causes corruption.

**To Reproduce**
1. Open a Shell
2. CD RAM:
3. MAKEDIR bla
4. RENAME bla bla/
5. DIR -> shows an empty directory
6. Press TAB for tab completion -> segfault

**Expected behaviour**
Show error message like "Invalid object name". That's what AmigaOS3 is doing.

**Screenshots**
![rename_ram](https://github.com/aros-development-team/AROS/assets/18250926/b286f748-e96c-4e67-b21c-342669f0dce2)

**Architecture**
 - linux (hosted)
 
Not yet tested:
 -  Amiga (including UAE, Vampire cards)
 - pc (native)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
**CPU**
 - x86_64
 
Not yet tested
 - i386
 - m68k
 - arm
 - ppc
 - other:

**Version**
Provide the Git ID from AboutAROS (call menu Wanderer>AROS>About)

**Additional context**
#0  0x000000005f40cf34 in __small_memcpy (src=0x0, dst=0x4168565d, size=255) at /home/mazze/projects/aros-src/arch/x86_64-all/exec/copymem.c:58
#1  0x000000005f40d14c in Exec_104_CopyMem (source=0x0, dest=0x4168565d, size=255) at /home/mazze/projects/aros-src/arch/x86_64-all/exec/copymem.c:177
#2  0x000000005f67fe40 in __inline_Exec_CopyMem (__arg1=0x0, __arg2=0x4168565d, __arg3=255, __SysBase=0x41000700) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/exec.h:1490
#3  0x000000005f6817eb in ExamineObject (handler=0x411af460, object=0x41356538, info=0x41685650) at /home/mazze/projects/aros-src/rom/filesys/ram/./filesystem.c:1091
#4  0x000000005f67e47e in CmdExamineNext (handler=0x411af460, info=0x41685650) at /home/mazze/projects/aros-src/rom/filesys/ram/./commands.c:1319
#5  0x000000005f67c271 in RAMMain (SysBase=0x41000700) at /home/mazze/projects/aros-src/rom/filesys/ram/./handler.c:256
#6  0x000000005f67b4a1 in ram_Handler (argptr=0x0, argsize=0, SysBase=0x41000700) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/filesys/ram/ram/ram_start.c:91
#7  0x000000005f52a0ef in CallEntry (argptr=0x0, argsize=0, entry=0x4113575c, me=0x41256f60) at /home/mazze/projects/aros-src/rom/dos/./exit.c:127

**Comment by Kalamatee** [comment]
Is it the command at fault, or the DOS Rename function? Can you check under AmigaOS what the OS calls behaviour is?

**Comment by mattrust** [comment]
The AROS Rename command works under AmigaOS.

**Comment by polluks** [comment]
This issue was fixed in MorphOS 3.18 by the way.

**Comment by mattrust** [comment]
@polluks I had tested it in AROS after reading the MorphOS release notes  ;-) Maybe I should try to contact the MorphOS developers.

**Comment by mattrust** [comment]
https://github.com/aros-development-team/AROS/commit/7ac3a70271da0c53bfb51304e031f1e054112990
fixed it.
