### ISSUE TITLE
No Sound on recent VMWare Player Versions!

### ISSUE THREAD

**Issue by aurabin** [aros-development-team/AROS#619]
**Describe the bug**
A clear and concisDitoe description of what the bug is.

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Architecture**
 - Amiga (including UAE, Vampire cards)
 - pc (native)
 - linux (hosted)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
**CPU**
 - i386
 - x86_64
 - m68k
 - arm
 - ppc
 - other:

**Version**
Provide the Git ID from AboutAROS (call menu Wanderer>AROS>About)

**Additional context**

**Comment by aurabin** [comment]
If you create a new Virtual Machine on  more recent VMWAre Player Versions or Player 17 and install eg AROS One 2.0 on it.. AHI only displays VOID: Options!

**Comment by Kalamatee** [comment]
<img width="524" alt="image" src="https://github.com/aros-development-team/AROS/assets/11282108/1c1d6f35-6df3-40f1-9ce9-d4cf8c83271e">

Audio works fine. I suspect you are missing the audio config in your .vmx file - and so it uses an unsupported hardware device.

**Comment by aurabin** [comment]
Sorry my hands are bound I can`t give you money ATM

Am Mi., 14. Juni 2023 um 12:33 Uhr schrieb Nick Andrews <
***@***.***>:

**Comment by aurabin** [comment]
Did you create a new  Virtual machine and installed AROS from Scratch?

Am Fr., 16. Juni 2023 um 14:47 Uhr schrieb Jorge Manuel Leal Ruivo <
***@***.***>:

**Comment by Kalamatee** [comment]
Its irrelevant - the problem is vmware automatically picks a default sound device that is not supported by AROS (so it is not a bug). You will need to edit your .vmx file for the virtual machine and make sure the following line is present -:

sound.virtualDev = "hdaudio"

**Comment by aurabin** [comment]
Ok, thanks for the clarification.

Am Fr., 16. Juni 2023 um 15:55 Uhr schrieb Nick Andrews <
***@***.***>:

**Comment by aurabin** [comment]
Can you e-mail me your IBAN number? It`s an alternative way to give you
some Money!

Am Sa., 17. Juni 2023 um 06:22 Uhr schrieb Jorge Manuel Leal Ruivo <
***@***.***>:
